[package]
name = "countme"
version = "0.1.0"
authors = ["Ali Soleimani <ali.soleimani@booking.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kmp = "0.1.1"
tokio = { version = "0.2", features = ["full"] }


